### ISSUE TITLE
Withdrawal proper format

### ISSUE THREAD

**Issue by Conqu3rer** [normpad/iotatipbot#4]
What is the proper format for using the Withdraw function? Many users are confused about the < > tags. Please give us a format. Thank you!

**Comment by normpad** [comment]
The format is:

> Withdraw
> 100 iota
> address: ADDRESSSTOWITHDRAWTO9999

Really it can be in any order that you like but you need 3 things: The word "withdraw" in either the subject or the body of the message; The amount you want to withdraw followed by iota; The address you want to withdraw to. I will remove the < > tags to maybe make it more clear.
