### ISSUE TITLE
Private Key Reuse Error

### ISSUE THREAD

**Issue by Tsangares** [normpad/iotatipbot#6]
Hey,
Just to let you know. I tried to deposit some money, first time depositing. The IOTA wallet won't let me because it says that the wallet I am trying to send to has already spent money & it would break the quantum tesseract and the fabric space time will cease to exist.
Don't know if it is a bug you wanna fix but it might be worth looking into.

Cheers,
I'm not British but I want to be,
 \- Wil

**Comment by normpad** [comment]
Could you please share with me the address that was given to you?

**Comment by Tsangares** [comment]
Address: FNGNOWPQIKIXR9HNCOEVMNU9DTIJGVTW9KLZDM9XVVIHNRVOZESIADSQDCMHAYXDLJCHONHGUNHODJAFCEPMGISHYC

**Comment by normpad** [comment]
Hmm, that's strange because that address does not have any transactions associated with it. The key reuse error should only occur when you are sending to an address that has already had iota sent from it. Maybe it could be a wallet issue?

**Comment by Tsangares** [comment]
Your probably right then. I thought it was odd that I could not find the wallet on iotasear.ch
Although I did try multiple nodes to connect to.

**Comment by Tsangares** [comment]
<img width="485" alt="screen shot 2017-11-24 at 10 16 02 pm" src="https://user-images.githubusercontent.com/9126482/33227992-2537d2b0-d165-11e7-9be6-47f23f1a505a.png">
<img width="618" alt="screen shot 2017-11-24 at 10 16 14 pm" src="https://user-images.githubusercontent.com/9126482/33227993-26b7497c-d165-11e7-895b-0dedc2e25799.png">

**Comment by Tsangares** [comment]
I think you are correct
I just tried to some iota to myself and it had the same error. I am going to reinstall the wallet.
